name: my first cicd pipeline

on:
  push:
    branches:
      - "main"

jobs:
  push_to_docker_hub:
    name: Push Image to Registry
    runs-on: ubuntu-latest
    steps:
      - name: copy the code
        uses: actions/checkout@v3

      - name: login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9

        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: zinoubm/batch

      - name: Print Meta Data
        run: echo ${{ steps.meta.outputs.tags }}

      - name: build and Push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc

        with:
          context: .
          push: true
          tags: zinoubm/batch:latest
          labels: ${{steps.meta.outputs.labels}}
